### ISSUE TITLE
EXAMPLE CODE FOR CNN3

### ISSUE THREAD

**Issue by sorobedio** [HSG-AIML/SANE#3]
Hello,
i think that it would be better if the example was for large CNN3  whose weights can be easily download

**Comment by kschuerholt** [comment]
Hi, thanks for the feedback! I've added corresponding code to run code on the small cnn sample dataset in `experiments`. Also, in `experiments` there's a quick-start notebook `cnn-cifar10_exploration.ipynb` to explore all things SANE pretraining, computing embeddings, etc. Hope that helps!

**Comment by sorobedio** [comment]
THANK YOU VERY MUCH
