### ISSUE TITLE
Did you train Resnet18 of cifar100 on epochs 60 only

### ISSUE THREAD

**Issue by sorobedio** [HSG-AIML/SANE#4]
I’m interested in knowing whether the method was trained solely with the base datasets provided in the examples—specifically for experiments using ResNet18 on CIFAR-10, CIFAR-100, and MiniImageNet. Could you please clarify if this is the case?

Thank you

**Comment by kschuerholt** [comment]
Hey, we specify the selections of epochs depending on the downstream task. For the generative task, it's in 5.2, see below. 

<img width="404" alt="grafik" src="https://github.com/user-attachments/assets/0defaf6e-c938-4429-8c32-003bbfcb3f21">

We used epochs 21-25 for pretraining of SANE. Unfortunately, the easily accessible dataset slice on zenodo is epoch 60. To fully reproduce the experiment setup, you'll have to download the full zoos from google drive and preprocess it. 


We're currently working on making the zoos easier to access, they are ~5TB each, not super easy to handle..

**Comment by sorobedio** [comment]
Thank you for the clarification. It seems that both the small CNN and large CNN models effectively cover the 21-25 range. Sticking with those options sounds like a solid choice.
